# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

  tasks:
  - stat: path=/home/{{ network_name }}_file.conf
    register: file_path
  - name: deleting the created file
    file: name=/home/{{ network_name }}_file.conf state=absent
    when: file_path.stat.exists == true
    ignore_errors: true

  - name: Ansible create sriov  network file
    copy:
     dest: "/home/{{ network_name }}_file.conf"
     content: |
       apiVersion: "kubernetes.com/v1"
       kind: Network
       metadata:
         name: {{ network_name }}
       plugin: sriov
       args: '[
         {
            "name": "{{ network_name }}",
            "type": "sriov",
            "if0": "{{intf}}",
            "ipam": {
            "type": "dhcp"
              }
           }
         ]'
    delegate_to: "localhost"

  - name : creating the sriov network as per the interface
    shell: "kubectl --kubeconfig={{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml create -f {{ network_name }}_file.conf"
    args:
        chdir: /home/
    delegate_to: "localhost"
    register: result
  - debug:
      var: result
  - stat: path=/home/{{ network_name }}_file.conf
    register: file_path
    delegate_to: "localhost"
  - name: deleting the created file
    file: name=/home/{{ network_name }}_file.conf state=absent
    when: file_path.stat.exists == true
    delegate_to: "localhost"
