# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
# This playbook delete weave conf file.
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    networking_plugin: "{{ networking_plugin }}"

  tasks:
  - name: Clean artifact path
    file:
      state: absent
      path: /etc/cni/net.d/

  - name: create the /etc/cni directory
    file: path=/etc/cni
          mode=0755
          state=directory

  - name: create the /etc/cni/net.d directory
    file: path=/etc/cni/net.d
          mode=0755
          state=directory

  - name: create multus-cni.conf file
    file: path=/root/multus-cni.conf state=touch
          mode=0644

  - name: write data in /root/multus-cni.conf file
    blockinfile:
      dest: /root/multus-cni.conf
      block: |
       {
         "name": "minion-cni-network",
         "type": "multus",
         "kubeconfig": "{{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml",
         "delegates": [{
               "type": "weave-net",
               "hairpinMode": true,
               "masterplugin": true
         }]
       }
    when: networking_plugin == "weave"

  - name: write data in /root/multus-cni.conf file
    blockinfile:
      dest: /root/multus-cni.conf
      block: |
       {
         "name": "minion-cni-network",
         "type": "multus",
         "kubeconfig": "{{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml",
         "delegates": [{
               "type": "flannel",
               "masterplugin": true,
               "delegate": {
                  "hairpinMode": true,
                  "isDefaultGateway": true
           }
         }]
       }
    when: networking_plugin == "flannel"

  - name: write data in /root/multus-cni.conf file
    blockinfile:
      dest: /root/multus-cni.conf
      block: |
       {
         "name": "minion-cni-network",
         "type": "multus",
         "kubeconfig": "{{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml"
       }
    when: networking_plugin != "flannel" and networking_plugin != "weave"

  - name: copy multus-cni.conf in /etc/cni/net.d/ folder
    shell: cp -r /root/multus-cni.conf /etc/cni/net.d/multus-cni.conf

  - lineinfile: dest=/etc/cni/net.d/multus-cni.conf state=absent regexp="ANSIBLE MANAGED BLOCK"

  - name: deleting created file
    file: name=/root/multus-cni.conf state=absent
    ignore_errors: true
