#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---

- hosts: "{{host_name}}" 
  become: true
  tasks:
    - name: edit file /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ osd_ip }} {{ osd_host_name }}"
      ignore_errors: true

- hosts: "{{host_name}}"
  become: true
  tasks:
     - shell: rm /root/.ssh/id_rsa
       ignore_errors: true
     - shell: echo -e y|ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
       ignore_errors: true

- hosts: "{{host_name}}"
  become: true
  tasks:
     - shell: sshpass -p {{passwd}} ssh-copy-id -o StrictHostKeyChecking=no {{user_id}}@{{osd_host_name}}
       ignore_errors: true

- hosts: "{{host_name}}"
  become: true
  tasks:
     - shell: sshpass -p {{passwd}} ssh-copy-id -o StrictHostKeyChecking=no {{user_id}}@{{osd_host_name}}
       ignore_errors: true

- hosts: "{{host_name}}" 
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  #vars:
   # Ceph_storage: "{{ceph_storage_size}}"
    #Ceph_Claim_name: "{{ceph_claim_name}}"
  
  environment:
#    http_proxy: "{{ http_proxy }}"
#    https_proxy: "{{ https_proxy }}"
#    no_proxy: "{{ no_proxy }}"
  #vars:
   # node_ip: "{{node_ip}}"

  tasks:

    - name: ceph-deploy forgetkeys 
      shell: ceph-deploy forgetkeys
      ignore_errors: true

    - name: ceph-deploy purge {{osd_host_name}}
      shell: ceph-deploy purge {{osd_host_name}}
      ignore_errors: true

    - name: ceph-deploy purgedata {{osd_host_name}} 
      shell: ceph-deploy purgedata {{osd_host_name}}
      ignore_errors: true

    - name: rm -f /etc/ceph/ceph.conf
      command: rm -f /etc/ceph/ceph.conf
      delegate_to: "{{osd_host_name}}"
#        state: absent 
      ignore_errors: true



    - name: deleting already existing file
      file:
       state: absent
       path: /var/lib/ceph/osd
      ignore_errors: true

    - name: sudo apt-get remove -y ceph-deploy
      shell: sudo apt-get remove -y ceph-deploy
      ignore_errors: true

    - name: deleting already existing directory
      file:
       state: absent
       path: /home/cluster-ceph
      ignore_errors: true

    #- name: sudo apt-get install -y python
     # command: sudo apt-get install -y python
     # register: cat
    #- debug: var=cat.stdout_lines

    - name: wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
      shell: wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
      register: cat
    - debug: var=cat.stdout_lines

    - name: echo deb http://download.ceph.com/debian-jewel/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
      command: echo deb http://download.ceph.com/debian-jewel/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
      register: cat
    - debug: var=cat.stdout_lines

    - name: sudo apt-get -qqy update && sudo apt-get install -qqy ntp ceph-deploy
      shell: sudo apt-get -qqy update && sudo apt-get install -qqy ntp ceph-deploy

    - name: create directory cluster-ceph
      file:
       state: directory
       path: /home/cluster-ceph
       mode: 0644

    - name: ceph-deploy new {{host_name}}
      command: ceph-deploy new {{host_name}}
      args:
        chdir: /home/cluster-ceph
      register: cat
    - debug: var=cat.stdout_lines

    - name: edit ceph.conf file
      lineinfile:
           dest: /home/cluster-ceph/ceph.conf
           line: "osd pool default size = 1"

#    - name: ceph-deploy install --release jewel {{host_name}}
#      command: ceph-deploy install --release jewel {{host_name}}
#      args:
        #chdir: "{{KUBERNETES_PATH}}cluster-ceph"
#        chdir: /home/cluster-ceph
#      register: cat
#    - debug: var=cat.stdout_lines

    #- name: ceph-deploy disk list {{host_name}}
     # command: ceph-deploy disk list {{host_name}}
      #args:
       # chdir: /home/cluster-ceph
      #ignore_errors: true

