#! Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---

- hosts: localhost
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
  tasks:
    - name: create directory at "{{ CURRENT_DIR }}projects" 
      file:
       state: directory	
       path: "{{ CURRENT_DIR }}projects/"
       mode: 0755
    - name: set path PROJECT_PATH("{{ CURRENT_DIR }}projects") in variable file   
      lineinfile:
        dest: "{{ VARIABLE_FILE }}"
        regexp: 'PROJECT_PATH:'
        line: 'PROJECT_PATH: "{{ CURRENT_DIR }}projects/"'

    - name: create directory at "{{ CURRENT_DIR }}projects/{{Project_name}}"
      file:
       state: directory	
       path: "{{ CURRENT_DIR }}projects/{{Project_name}}"
       mode: 0755

    - name: Copy inventery file to "{{ CURRENT_DIR }}projects/{{Project_name}}" 
      copy:
           src: "{{SRC_PACKAGE_PATH}}inventory.cfg"
           dest: "{{ CURRENT_DIR }}projects/{{Project_name}}/inventory.cfg"
    - name: remove old kargo
      file:
       state: absent
       path: "{{KARGO_PATH}}"
    - name: create karo dir
      file:
       state: directory	
       path: "{{ CURRENT_DIR }}kargo_folder"
       mode: 0644
    - name: set kargo path
      lineinfile:
        dest: "{{ VARIABLE_FILE }}"
        regexp: 'KARGO_PATH:'
        line: 'KARGO_PATH: "{{ CURRENT_DIR }}kargo_folder/"'
